require('dotenv').config();
const express = require('express');
const cors = require('cors');
const path = require('path');
const connectDB = require('./config/db');
const postsRouter = require('./routes/posts');
const authRouter = require('./routes/auth');
const categoriesRouter = require('./routes/categories');
const errorHandler = require('./middleware/errorHandler');
const app = express();
const PORT = process.env.PORT || 5000;
connectDB();
app.use(cors());
app.use(express.json());
app.use('/uploads', express.static(path.join(__dirname, 'uploads')));
app.use('/api/posts', postsRouter);
app.use('/api/auth', authRouter);
app.use('/api/categories', categoriesRouter);
app.use(errorHandler);
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
